name: Example CI

# Controls when the action will run. 
on:
  push:
    branches: [ beta_x.0 ]
    paths-ignore:
      - docs/
      - examples/
      - .gitignore
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - SECURITY.md
      
  pull_request:
    branches: [ beta_x.0 ]
    paths-ignore:
      - docs/
      - examples/
      - .gitignore
      - README.md
      - LICENSE
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - SECURITY.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Instal iVerilog
        run: sudo apt install iverilog gtkwave yosys binutils 

      - name: Make Tests
        run: make
